### ISSUE TITLE
Release a new version compatible with Micronaut 3.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-hibernate-validator#135]
Please follow the instructions in https://github.com/micronaut-projects/micronaut-core/issues/5607 and update that core issue with the information related to the upgrade.

**Comment by nrsina** [comment]
Hello. Thanks for your efforts on Micronaut.
When do you think this gets finished? we need to use it in our Micronaut project as soon as possible.
Kind regards
