### ISSUE TITLE
Leverage HibernateValidatorEnhancedBean provided extension point for tighter integration with Hibernate Validator

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-hibernate-validator#49]
There is an interface to be implemented to provide Hibernate Validator non reflective info about bean.
[`org.hibernate.validator.engine.HibernateValidatorEnhancedBean`](https://github.com/hibernate/hibernate-validator/blob/master/engine/src/main/java/org/hibernate/validator/engine/HibernateValidatorEnhancedBean.java).

Maybe it's worth to implement it at some phase of Micronaut metadata processing for better / tighter integration?

here is an example which uses ByteBuddy, so I put it here just for to link relevant info, as Micronaut probably be using it's own approach for such tasks.

https://github.com/marko-bekhta/hibernate-validator/blob/2163cceec2013cd777a9ce643cf165e764c8c7be/engine/src/test/java/org/hibernate/validator/test/internal/metadata/bytebuddy/ByteBuddyWrapperTest.java

**Comment by graemerocher** [comment]
Possibly, PRs are welcome in this area. Currently since Micronaut has built in validation that is reflection free we recommend users use that instead of Hibernate Validator

**Comment by soberich** [comment]
Agree 👍
